# Generated by Django 2.1 on 2018-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
