# Generated by Django 2.1 on 2018-08-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='img',
            name='out',
            field=models.CharField(default='', max_length=50),
        ),
    ]
